import { createI18n } from 'vue-i18n'

const messages = {
  fr: {
    bulkImport: { chooseFile: 'Choisir un fichier', formats: 'Formats : CSV, JSON, Excel, SQL/Dump, Access (.mdb/.accdb)', paste: 'Collez ici un CSV ou un JSON', preview: 'Aperçu : {count} ligne(s)', importing: 'Importation...', importRows: 'Importer {count} ligne(s)' },
    language: 'Langue',
    brand: { name: 'School Store', tagline: 'gestion scolaire' },
    theme: { label: 'Apparence', system: 'Système', light: 'Clair', dark: 'Sombre' },
    layout: { openMenu: 'Ouvrir le menu', closeMenu: 'Fermer le menu' },
    languages: { fr: 'Français', en: 'English', es: 'Español', ar: 'العربية' },
    nav: { dashboard: 'Tableau de bord', products: 'Produits', categories: 'Catégories', clients: 'Clients', reports: 'Rapports', team: 'Équipe', newInvoice: 'Nouvelle facture', invoices: 'Factures' },
    pages: { dashboard: 'Tableau de bord', products: 'Gestion des produits', categories: 'Gestion des catégories', clients: 'Gestion des clients', reports: 'Rapports et statistiques', team: 'Équipe et organisation', newInvoice: 'Nouvelle facture', invoices: 'Historique des factures', detail: 'Détail de la facture' },
    actions: { logout: 'Déconnexion', recent: 'Dernières factures', viewAll: 'Voir tout', refresh: 'Actualiser' },
    dashboard: { products: 'Produits', categories: 'Catégories', clients: 'Clients', invoices: 'Factures totales', pending: 'Factures en attente', revenue: "Chiffre d'affaires", lowStock: 'Stock bas', createInvoice: 'Créer une facture', manageProducts: 'Gérer les produits', manageClients: 'Gérer les clients', history: "Voir l'historique", noInvoices: 'Aucune facture', greeting: 'Bonjour, {name}', welcomeCopy: "Suivez l'activite de votre boutique scolaire en un coup d'oeil.", unknownClient: 'Client non renseigné' },
    status: { paid: 'Payée', pending: 'En attente', cancelled: 'Annulée' },
    common: { save: 'Enregistrer', cancel: 'Annuler', edit: 'Modifier', delete: 'Supprimer', loading: 'Chargement...', none: 'Aucun', search: 'Rechercher', import: 'Importer en masse', importHint: 'Vous pouvez aussi coller les données manuellement. La première ligne CSV doit contenir les noms des colonnes.', create: 'Créer', close: 'Fermer', name: 'Nom', email: 'Email', phone: 'Téléphone', address: 'Adresse', description: 'Description', notes: 'Notes', price: 'Prix', stock: 'Stock', barcode: 'Code-barres', category: 'Catégorie', image: 'Image', allStatuses: 'Tous les statuts', noResults: 'Aucun résultat', notFound: 'Page introuvable' },
    login: { subtitle: 'Connectez-vous pour continuer', signIn: 'Connexion', signUp: 'Inscription', fullName: 'Nom complet', role: 'Rôle', agent: 'Agent (caisse)', manager: 'Manager', password: 'Mot de passe', wait: 'Patientez...', submitSignIn: 'Se connecter', submitSignUp: 'Créer le compte', demo: 'Compte démo (SQLite)', adapter: 'Adapter actif' },
    productsView: { title: 'Produits', new: 'Nouveau produit', noProducts: 'Aucun produit', edit: 'Modifier le produit', newTitle: 'Nouveau produit', imageUrl: 'URL de l’image ou fichier', noCategory: 'Aucune', importing: 'Importer des produits', inStock: 'en stock', scanBarcode: 'Scanner le code-barres', scanProduct: 'Scanner un produit', barcodeHint: 'Scannez le code avec la camera ou saisissez-le manuellement.', duplicateBarcode: 'Ce code-barres est deja associe au produit « {name} ».', adjustStock: 'Ajuster le stock', adjustStockTitle: 'Ajuster le stock : {name}', adjustCurrentStock: 'Stock actuel', adjustQuantity: 'Quantité (+ ou -)', adjustQuantityHint: 'Utilisez une valeur positive pour ajouter, négative pour retirer.', adjustReason: 'Motif', adjustSubmit: 'Appliquer', reasonCorrection: 'Correction d’inventaire', reasonRestock: 'Réapprovisionnement', reasonDamage: 'Produit endommagé', reasonLoss: 'Perte / vol', reasonOther: 'Autre', lowStockThreshold: 'Seuil de stock bas', lowStockThresholdHint: 'Laissez vide pour utiliser le seuil par défaut de l’application.' },
    categoriesView: { title: 'Catégories', new: 'Nouvelle catégorie', edit: 'Modifier la catégorie', importing: 'Importer des catégories' },
    clientsView: { title: 'Clients', new: 'Nouveau client', edit: 'Modifier le client', importing: 'Importer des clients', discount: 'Remise générale (%)', pricing: 'Tarif produit spécifique', noClients: 'Aucun client', noClient: 'Sans client', balanceDue: 'Solde dû', statement: 'Relevé de compte', statementTitle: 'Relevé de compte : {name}', statementEmpty: 'Aucune facture impayée.' },
    reports: { title: 'Rapports', dateFrom: 'Du', dateTo: 'Au', thisMonth: 'Ce mois-ci', last7Days: '7 derniers jours', allTime: 'Depuis le début', totalRevenue: "Chiffre d'affaires", invoiceCount: 'Factures', averageSale: 'Vente moyenne', outstandingBalance: 'Solde impayé', topProducts: 'Produits les plus vendus', topClients: 'Meilleurs clients', salesByAgent: 'Ventes par agent', product: 'Produit', quantitySold: 'Qté vendue', revenue: 'Chiffre d’affaires', client: 'Client', agent: 'Agent', noData: 'Aucune donnée pour cette période', exportCsv: 'Exporter en CSV' },
    team: { title: 'Équipe', unavailable: 'La gestion d’équipe nécessite l’adaptateur Supabase.', profileShortcut: 'Gérer organisation et équipe', updateOrganization: 'Modifier organisation', organizationName: 'Nom de l’organisation', organizationSlug: 'Identifiant URL', organizationUpdated: 'Organisation mise à jour.', status: 'Statut', currency: 'Devise', members: 'Membres', member: 'Membre', noMembers: 'Aucun membre', role: 'Rôle', inviteUser: 'Créer un utilisateur', inviteHint: 'Un email d’invitation sera envoyé pour définir son mot de passe.', sendInvite: 'Envoyer l’invitation', invitationSent: 'Invitation envoyée.', roles: { owner: 'Propriétaire', manager: 'Manager', cashier: 'Caissier', stockManager: 'Gestionnaire de stock', accountant: 'Comptable', viewer: 'Lecteur' }, statuses: { active: 'Actif', invited: 'Invité', suspended: 'Suspendu' } },
    organizations: { title: 'Organisations', shortcut: 'Gérer les organisations', create: 'Créer une organisation', edit: 'Modifier l’organisation', empty: 'Aucune organisation', name: 'Nom', slug: 'Identifiant URL', status: 'Statut', email: 'Email', phone: 'Téléphone', address: 'Adresse', active: 'Active', suspended: 'Suspendue', pending: 'En attente', cancelled: 'Annulée', manageTeam: 'Gérer l’équipe', saved: 'Organisation enregistrée.', deleted: 'Organisation supprimée.', confirmDelete: 'Supprimer {name} ?' },
    profile: { title: 'Mon profil', shortcut: 'Gérer mon profil', fullName: 'Nom complet', role: 'Rôle', saved: 'Profil mis à jour.' },
    invoicesView: { title: 'Historique des factures', search: 'Rechercher (n° facture, client...)', selectAll: 'Sélectionner toutes les factures', invoiceNumber: 'N° Facture', createdBy: 'Créée par', client: 'Client', date: 'Date', total: 'Total', status: 'Statut', actions: 'Actions', noInvoices: 'Aucune facture', view: 'Voir la facture', delete: 'Supprimer la facture', bulkDelete: 'Supprimer les factures sélectionnées', confirmDelete: 'Supprimer la facture {number} ?', confirmBulk: 'Supprimer {count} facture(s) sélectionnée(s) ?' },
    invoiceCreate: { productSearch: 'Rechercher par nom ou code-barres', clientSearch: 'Rechercher un client (nom, email ou téléphone)', selectedClient: 'Client sélectionné : {name}', customerName: 'Nom du client (optionnel)', empty: 'Le panier est vide', scanHint: 'Scannez un produit ou utilisez la saisie manuelle', clear: 'Vider', payment: 'Paiement', received: 'Montant reçu', change: 'Monnaie à rendre', remaining: 'Reste à payer', validate: 'Valider la facture', success: 'Facture validée avec succès !' },
    pos: { subtotal: 'Sous-total', discount: 'Remise', total: 'Total', proceedPayment: 'Proceder au paiement', addProduct: 'Ajouter un produit', chooseClient: 'Choisir un client', clearCart: 'Vider le panier', processingPayment: 'Validation...', outOfStock: 'Rupture de stock', stockAvailable: 'Stock : {stock}', inCart: 'Dans le panier : {quantity}', amountReceived: 'Montant recu', paymentMethod: 'Mode de paiement', discountPercent: 'Remise (%)', changeDue: 'Monnaie a rendre', quickAmounts: 'Montants rapides', cash: 'Especes', card: 'Carte', transfer: 'Virement', other: 'Autre', quantityOf: 'Quantité de {name}', decreaseQuantity: 'Diminuer la quantité', increaseQuantity: 'Augmenter la quantité', unitPrice: 'Prix unit.', lineTotal: 'Total', removeFromInvoice: 'Retirer {name}', removeFromInvoiceTitle: 'Retirer de la facture', stock: 'Stock : {stock}' },
    detail: { back: 'Retour', date: 'Date', customer: 'Client', createdBy: 'Créée par', status: 'Statut', product: 'Produit', quantity: 'Qté', unitPrice: 'Prix unit.', total: 'Total', print: 'Imprimer', paid: 'Payé', delete: 'Supprimer la facture', subtotal: 'Sous-total', discount: 'Remise', remaining: 'Reste a payer', paymentHistory: 'Historique des paiements', noPayments: 'Aucun paiement enregistre.', returnItems: 'Retourner des articles', returned: '{count} retourné(s)', returnMax: 'max {max}', noReturnableItems: 'Aucun article à retourner', confirmReturn: 'Confirmer le retour' },
    scanner: { activate: 'Cliquez pour activer le scanner', start: 'Démarrer le scanner', retry: 'Réessayer', stop: 'Arrêter', manual: 'Saisie manuelle', code: 'Code-barres ou QR code', validate: 'Valider', last: 'Dernier code scanné', useDatalogic: 'Utiliser le scanner Datalogic', hardwareScanner: 'Scanner Datalogic', waitingForScan: 'En attente d\'un scan...' },
    hardware: { title: 'Équipement', scanner: 'Scanner Datalogic', printer: 'Imprimante thermique', connect: 'Connecter', disconnect: 'Déconnecter', connected: 'Connecté', disconnected: 'Déconnecté', autoScan: 'Scanner automatique', autoPrint: 'Impression automatique après paiement', testPrint: 'Test d\'impression' }
  },
  en: {
    bulkImport: { chooseFile: 'Choose a file', formats: 'Formats: CSV, JSON, Excel, SQL/Dump, Access (.mdb/.accdb)', paste: 'Paste CSV or JSON here', preview: 'Preview: {count} row(s)', importing: 'Importing...', importRows: 'Import {count} row(s)' },
    language: 'Language',
    brand: { name: 'School Store', tagline: 'school management' },
    theme: { label: 'Appearance', system: 'System', light: 'Light', dark: 'Dark' },
    layout: { openMenu: 'Open menu', closeMenu: 'Close menu' },
    languages: { fr: 'Français', en: 'English', es: 'Español', ar: 'العربية' },
    nav: { dashboard: 'Dashboard', products: 'Products', categories: 'Categories', clients: 'Clients', reports: 'Reports', team: 'Team', newInvoice: 'New invoice', invoices: 'Invoices' },
    pages: { dashboard: 'Dashboard', products: 'Product management', categories: 'Category management', clients: 'Client management', reports: 'Reports & analytics', team: 'Team & organization', newInvoice: 'New invoice', invoices: 'Invoice history', detail: 'Invoice details' },
    actions: { logout: 'Sign out', recent: 'Recent invoices', viewAll: 'View all', refresh: 'Refresh' },
    dashboard: { products: 'Products', categories: 'Categories', clients: 'Clients', invoices: 'Total invoices', pending: 'Pending invoices', revenue: 'Revenue', lowStock: 'Low stock', createInvoice: 'Create invoice', manageProducts: 'Manage products', manageClients: 'Manage clients', history: 'View history', noInvoices: 'No invoices', greeting: 'Hello, {name}', welcomeCopy: 'Follow your school store activity at a glance.', unknownClient: 'Client not provided' },
    status: { paid: 'Paid', pending: 'Pending', cancelled: 'Cancelled' },
    common: { save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', loading: 'Loading...', none: 'None', search: 'Search', import: 'Bulk import', importHint: 'You can also paste data manually. The first CSV row must contain column names.', create: 'Create', close: 'Close', name: 'Name', email: 'Email', phone: 'Phone', address: 'Address', description: 'Description', notes: 'Notes', price: 'Price', stock: 'Stock', barcode: 'Barcode', category: 'Category', image: 'Image', allStatuses: 'All statuses', noResults: 'No results', notFound: 'Page not found' },
    login: { subtitle: 'Sign in to continue', signIn: 'Sign in', signUp: 'Sign up', fullName: 'Full name', role: 'Role', agent: 'Agent (cashier)', manager: 'Manager', password: 'Password', wait: 'Please wait...', submitSignIn: 'Sign in', submitSignUp: 'Create account', demo: 'Demo account (SQLite)', adapter: 'Active adapter' },
    productsView: { title: 'Products', new: 'New product', noProducts: 'No products', edit: 'Edit product', newTitle: 'New product', imageUrl: 'Image URL or file', noCategory: 'None', importing: 'Import products', inStock: 'In stock', scanBarcode: 'Scan barcode', scanProduct: 'Scan product', barcodeHint: 'Scan the code with the camera or enter it manually.', duplicateBarcode: 'This barcode is already assigned to “{name}”.', adjustStock: 'Adjust stock', adjustStockTitle: 'Adjust stock: {name}', adjustCurrentStock: 'Current stock', adjustQuantity: 'Quantity (+ or -)', adjustQuantityHint: 'Use a positive value to add, negative to remove.', adjustReason: 'Reason', adjustSubmit: 'Apply', reasonCorrection: 'Inventory correction', reasonRestock: 'Restock', reasonDamage: 'Damaged goods', reasonLoss: 'Loss / theft', reasonOther: 'Other', lowStockThreshold: 'Low-stock threshold', lowStockThresholdHint: 'Leave empty to use the app default threshold.' },
    categoriesView: { title: 'Categories', new: 'New category', edit: 'Edit category', importing: 'Import categories' },
    clientsView: { title: 'Clients', new: 'New client', edit: 'Edit client', importing: 'Import clients', discount: 'General discount (%)', pricing: 'Specific product price', noClients: 'No clients', noClient: 'No client', balanceDue: 'Balance due', statement: 'Account statement', statementTitle: 'Account statement: {name}', statementEmpty: 'No unpaid invoices.' },
    reports: { title: 'Reports', dateFrom: 'From', dateTo: 'To', thisMonth: 'This month', last7Days: 'Last 7 days', allTime: 'All time', totalRevenue: 'Revenue', invoiceCount: 'Invoices', averageSale: 'Average sale', outstandingBalance: 'Outstanding balance', topProducts: 'Top products', topClients: 'Top clients', salesByAgent: 'Sales by agent', product: 'Product', quantitySold: 'Qty sold', revenue: 'Revenue', client: 'Client', agent: 'Agent', noData: 'No data for this period', exportCsv: 'Export CSV' },
    team: { title: 'Team', unavailable: 'Team management requires the Supabase adapter.', profileShortcut: 'Manage organization and team', updateOrganization: 'Edit organization', organizationName: 'Organization name', organizationSlug: 'URL identifier', organizationUpdated: 'Organization updated.', status: 'Status', currency: 'Currency', members: 'Members', member: 'Member', noMembers: 'No members', role: 'Role', inviteUser: 'Create user', inviteHint: 'An invitation email will be sent so the user can set a password.', sendInvite: 'Send invitation', invitationSent: 'Invitation sent.', roles: { owner: 'Owner', manager: 'Manager', cashier: 'Cashier', stockManager: 'Stock manager', accountant: 'Accountant', viewer: 'Viewer' }, statuses: { active: 'Active', invited: 'Invited', suspended: 'Suspended' } },
    organizations: { title: 'Organizations', shortcut: 'Manage organizations', create: 'Create organization', edit: 'Edit organization', empty: 'No organizations', name: 'Name', slug: 'URL identifier', status: 'Status', email: 'Email', phone: 'Phone', address: 'Address', active: 'Active', suspended: 'Suspended', pending: 'Pending', cancelled: 'Cancelled', manageTeam: 'Manage team', saved: 'Organization saved.', deleted: 'Organization deleted.', confirmDelete: 'Delete {name}?' },
    profile: { title: 'My profile', shortcut: 'Manage my profile', fullName: 'Full name', role: 'Role', saved: 'Profile updated.' },
    invoicesView: { title: 'Invoice history', search: 'Search (invoice no., client...)', selectAll: 'Select all invoices', invoiceNumber: 'Invoice no.', createdBy: 'Created by', client: 'Client', date: 'Date', total: 'Total', status: 'Status', actions: 'Actions', noInvoices: 'No invoices', view: 'View invoice', delete: 'Delete invoice', bulkDelete: 'Delete selected invoices', confirmDelete: 'Delete invoice {number}?', confirmBulk: 'Delete {count} selected invoice(s)?' },
    invoiceCreate: { productSearch: 'Search by name or barcode', clientSearch: 'Search a client (name, email or phone)', selectedClient: 'Selected client: {name}', customerName: 'Client name (optional)', empty: 'Cart is empty', scanHint: 'Scan a product or use manual entry', clear: 'Clear', payment: 'Payment', received: 'Amount received', change: 'Change', remaining: 'Remaining to pay', validate: 'Validate invoice', success: 'Invoice validated successfully!' },
    pos: { subtotal: 'Subtotal', discount: 'Discount', total: 'Total', proceedPayment: 'Proceed to payment', addProduct: 'Add product', chooseClient: 'Choose client', clearCart: 'Clear cart', processingPayment: 'Validating...', outOfStock: 'Out of stock', stockAvailable: 'Stock: {stock}', inCart: 'In cart: {quantity}', amountReceived: 'Amount received', paymentMethod: 'Payment method', discountPercent: 'Discount (%)', changeDue: 'Change due', quickAmounts: 'Quick amounts', cash: 'Cash', card: 'Card', transfer: 'Bank transfer', other: 'Other', quantityOf: 'Quantity of {name}', decreaseQuantity: 'Decrease quantity', increaseQuantity: 'Increase quantity', unitPrice: 'Unit price', lineTotal: 'Total', removeFromInvoice: 'Remove {name}', removeFromInvoiceTitle: 'Remove from invoice', stock: 'Stock: {stock}' },
    detail: { back: 'Back', date: 'Date', customer: 'Client', createdBy: 'Created by', status: 'Status', product: 'Product', quantity: 'Qty', unitPrice: 'Unit price', total: 'Total', print: 'Print', paid: 'Paid', delete: 'Delete invoice', subtotal: 'Subtotal', discount: 'Discount', remaining: 'Remaining to pay', paymentHistory: 'Payment history', noPayments: 'No payments recorded.', returnItems: 'Return items', returned: '{count} returned', returnMax: 'max {max}', noReturnableItems: 'No items to return', confirmReturn: 'Confirm return' },
    scanner: { activate: 'Click to activate scanner', start: 'Start scanner', retry: 'Retry', stop: 'Stop', manual: 'Manual entry', code: 'Barcode or QR code', validate: 'Validate', last: 'Last scanned code', useDatalogic: 'Use Datalogic Scanner', hardwareScanner: 'Datalogic Scanner', waitingForScan: 'Waiting for barcode scan...' },
    hardware: { title: 'Hardware', scanner: 'Datalogic Scanner', printer: 'Thermal Printer', connect: 'Connect', disconnect: 'Disconnect', connected: 'Connected', disconnected: 'Disconnected', autoScan: 'Auto Scanner', autoPrint: 'Auto-print after payment', testPrint: 'Test Print' }
  },
  es: {
    bulkImport: { chooseFile: 'Elegir un archivo', formats: 'Formatos: CSV, JSON, Excel, SQL/Dump, Access (.mdb/.accdb)', paste: 'Pega aquí un CSV o JSON', preview: 'Vista previa: {count} fila(s)', importing: 'Importando...', importRows: 'Importar {count} fila(s)' },
    language: 'Idioma',
    brand: { name: 'School Store', tagline: 'gestión escolar' },
    theme: { label: 'Apariencia', system: 'Sistema', light: 'Claro', dark: 'Oscuro' },
    layout: { openMenu: 'Abrir menú', closeMenu: 'Cerrar menú' },
    languages: { fr: 'Français', en: 'English', es: 'Español', ar: 'العربية' },
    nav: { dashboard: 'Panel', products: 'Productos', categories: 'Categorías', clients: 'Clientes', reports: 'Informes', team: 'Equipo', newInvoice: 'Nueva factura', invoices: 'Facturas' },
    pages: { dashboard: 'Panel', products: 'Gestión de productos', categories: 'Gestión de categorías', clients: 'Gestión de clientes', reports: 'Informes y estadísticas', team: 'Equipo y organización', newInvoice: 'Nueva factura', invoices: 'Historial de facturas', detail: 'Detalle de factura' },
    actions: { logout: 'Cerrar sesión', recent: 'Facturas recientes', viewAll: 'Ver todo', refresh: 'Actualizar' },
    dashboard: { products: 'Productos', categories: 'Categorías', clients: 'Clientes', invoices: 'Facturas totales', pending: 'Facturas pendientes', revenue: 'Ingresos', lowStock: 'Stock bajo', createInvoice: 'Crear factura', manageProducts: 'Gestionar productos', manageClients: 'Gestionar clientes', history: 'Ver historial', noInvoices: 'No hay facturas', greeting: 'Hola, {name}', welcomeCopy: 'Sigue la actividad de tu tienda escolar de un vistazo.', unknownClient: 'Cliente no indicado' },
    status: { paid: 'Pagada', pending: 'Pendiente', cancelled: 'Cancelada' },
    common: { save: 'Guardar', cancel: 'Cancelar', edit: 'Editar', delete: 'Eliminar', loading: 'Cargando...', none: 'Ninguno', search: 'Buscar', import: 'Importar', importHint: 'También puedes pegar los datos manualmente. La primera fila CSV debe contener los nombres de las columnas.', create: 'Crear', close: 'Cerrar', name: 'Nombre', email: 'Email', phone: 'Teléfono', address: 'Dirección', description: 'Descripción', notes: 'Notas', price: 'Precio', stock: 'Stock', barcode: 'Código de barras', category: 'Categoría', image: 'Imagen', allStatuses: 'Todos los estados', noResults: 'Sin resultados', notFound: 'Página no encontrada' },
    login: { subtitle: 'Inicia sesión para continuar', signIn: 'Iniciar sesión', signUp: 'Registro', fullName: 'Nombre completo', role: 'Rol', agent: 'Agente (caja)', manager: 'Gerente', password: 'Contraseña', wait: 'Espera...', submitSignIn: 'Iniciar sesión', submitSignUp: 'Crear cuenta', demo: 'Cuenta demo (SQLite)', adapter: 'Adaptador activo' },
    productsView: { title: 'Productos', new: 'Nuevo producto', noProducts: 'No hay productos', edit: 'Editar producto', newTitle: 'Nuevo producto', imageUrl: 'URL o archivo de imagen', noCategory: 'Ninguna', importing: 'Importar productos', inStock: 'en stock', scanBarcode: 'Escanear código de barras', scanProduct: 'Escanear producto', barcodeHint: 'Escanea el código con la cámara o introdúcelo manualmente.', duplicateBarcode: 'Este código ya está asignado al producto “{name}”.', adjustStock: 'Ajustar stock', adjustStockTitle: 'Ajustar stock: {name}', adjustCurrentStock: 'Stock actual', adjustQuantity: 'Cantidad (+ o -)', adjustQuantityHint: 'Usa un valor positivo para añadir, negativo para retirar.', adjustReason: 'Motivo', adjustSubmit: 'Aplicar', reasonCorrection: 'Corrección de inventario', reasonRestock: 'Reabastecimiento', reasonDamage: 'Producto dañado', reasonLoss: 'Pérdida / robo', reasonOther: 'Otro', lowStockThreshold: 'Umbral de stock bajo', lowStockThresholdHint: 'Déjalo vacío para usar el umbral predeterminado de la aplicación.' },
    categoriesView: { title: 'Categorías', new: 'Nueva categoría', edit: 'Editar categoría', importing: 'Importar categorías' },
    clientsView: { title: 'Clientes', new: 'Nuevo cliente', edit: 'Editar cliente', importing: 'Importar clientes', discount: 'Descuento general (%)', pricing: 'Precio específico del producto', noClients: 'No hay clientes', noClient: 'Sin cliente', balanceDue: 'Saldo pendiente', statement: 'Estado de cuenta', statementTitle: 'Estado de cuenta: {name}', statementEmpty: 'No hay facturas pendientes.' },
    reports: { title: 'Informes', dateFrom: 'Desde', dateTo: 'Hasta', thisMonth: 'Este mes', last7Days: 'Últimos 7 días', allTime: 'Todo el tiempo', totalRevenue: 'Ingresos', invoiceCount: 'Facturas', averageSale: 'Venta media', outstandingBalance: 'Saldo pendiente', topProducts: 'Productos más vendidos', topClients: 'Mejores clientes', salesByAgent: 'Ventas por agente', product: 'Producto', quantitySold: 'Cant. vendida', revenue: 'Ingresos', client: 'Cliente', agent: 'Agente', noData: 'No hay datos para este período', exportCsv: 'Exportar CSV' },
    team: { title: 'Equipo', unavailable: 'La gestión de equipo requiere el adaptador Supabase.', profileShortcut: 'Gestionar organización y equipo', updateOrganization: 'Editar organización', organizationName: 'Nombre de la organización', organizationSlug: 'Identificador URL', organizationUpdated: 'Organización actualizada.', status: 'Estado', currency: 'Moneda', members: 'Miembros', member: 'Miembro', noMembers: 'No hay miembros', role: 'Rol', inviteUser: 'Crear usuario', inviteHint: 'Se enviará un correo de invitación para definir la contraseña.', sendInvite: 'Enviar invitación', invitationSent: 'Invitación enviada.', roles: { owner: 'Propietario', manager: 'Manager', cashier: 'Cajero', stockManager: 'Gestor de stock', accountant: 'Contable', viewer: 'Lector' }, statuses: { active: 'Activo', invited: 'Invitado', suspended: 'Suspendido' } },
    organizations: { title: 'Organizaciones', shortcut: 'Gestionar organizaciones', create: 'Crear organización', edit: 'Editar organización', empty: 'No hay organizaciones', name: 'Nombre', slug: 'Identificador URL', status: 'Estado', email: 'Email', phone: 'Teléfono', address: 'Dirección', active: 'Activa', suspended: 'Suspendida', pending: 'Pendiente', cancelled: 'Cancelada', manageTeam: 'Gestionar equipo', saved: 'Organización guardada.', deleted: 'Organización eliminada.', confirmDelete: '¿Eliminar {name}?' },
    profile: { title: 'Mi perfil', shortcut: 'Gestionar mi perfil', fullName: 'Nombre completo', role: 'Rol', saved: 'Perfil actualizado.' },
    invoicesView: { title: 'Historial de facturas', search: 'Buscar (nº factura, cliente...)', selectAll: 'Seleccionar todas las facturas', invoiceNumber: 'N.º de factura', createdBy: 'Creada por', client: 'Cliente', date: 'Fecha', total: 'Total', status: 'Estado', actions: 'Acciones', noInvoices: 'No hay facturas', view: 'Ver factura', delete: 'Eliminar factura', bulkDelete: 'Eliminar facturas seleccionadas', confirmDelete: '¿Eliminar la factura {number}?', confirmBulk: '¿Eliminar {count} factura(s) seleccionada(s)?' },
    invoiceCreate: { productSearch: 'Buscar por nombre o código de barras', clientSearch: 'Buscar cliente (nombre, email o teléfono)', selectedClient: 'Cliente seleccionado: {name}', customerName: 'Nombre del cliente (opcional)', empty: 'El carrito está vacío', scanHint: 'Escanea un producto o usa la entrada manual', clear: 'Vaciar', payment: 'Pago', received: 'Importe recibido', change: 'Cambio', remaining: 'Pendiente de pago', validate: 'Validar factura', success: '¡Factura validada correctamente!' },
    pos: { subtotal: 'Subtotal', discount: 'Descuento', total: 'Total', proceedPayment: 'Proceder al pago', addProduct: 'Añadir producto', chooseClient: 'Elegir cliente', clearCart: 'Vaciar carrito', processingPayment: 'Validando...', outOfStock: 'Sin existencias', stockAvailable: 'Stock: {stock}', inCart: 'En carrito: {quantity}', amountReceived: 'Importe recibido', paymentMethod: 'Método de pago', discountPercent: 'Descuento (%)', changeDue: 'Cambio a devolver', quickAmounts: 'Importes rápidos', cash: 'Efectivo', card: 'Tarjeta', transfer: 'Transferencia', other: 'Otro', quantityOf: 'Cantidad de {name}', decreaseQuantity: 'Disminuir cantidad', increaseQuantity: 'Aumentar cantidad', unitPrice: 'Precio unit.', lineTotal: 'Total', removeFromInvoice: 'Quitar {name}', removeFromInvoiceTitle: 'Quitar de la factura', stock: 'Stock: {stock}' },
    detail: { back: 'Volver', date: 'Fecha', customer: 'Cliente', createdBy: 'Creada por', status: 'Estado', product: 'Producto', quantity: 'Cant.', unitPrice: 'Precio unit.', total: 'Total', print: 'Imprimir', paid: 'Pagado', delete: 'Eliminar factura', subtotal: 'Subtotal', discount: 'Descuento', remaining: 'Pendiente de pago', paymentHistory: 'Historial de pagos', noPayments: 'No hay pagos registrados.', returnItems: 'Devolver artículos', returned: '{count} devuelto(s)', returnMax: 'máx {max}', noReturnableItems: 'No hay artículos para devolver', confirmReturn: 'Confirmar devolución' },
    scanner: { activate: 'Pulsa para activar el escáner', start: 'Iniciar escáner', retry: 'Reintentar', stop: 'Detener', manual: 'Entrada manual', code: 'Código de barras o QR', validate: 'Validar', last: 'Último código escaneado', useDatalogic: 'Usar Escáner Datalogic', hardwareScanner: 'Escáner Datalogic', waitingForScan: 'Esperando escaneo de código de barras...' },
    hardware: { title: 'Equipo', scanner: 'Escáner Datalogic', printer: 'Impresora Térmica', connect: 'Conectar', disconnect: 'Desconectar', connected: 'Conectado', disconnected: 'Desconectado', autoScan: 'Escaneo Automático', autoPrint: 'Impresión automática después del pago', testPrint: 'Prueba de Impresión' }
  },
  ar: {
    bulkImport: { chooseFile: 'اختيار ملف', formats: 'الصيغ: CSV وJSON وExcel وSQL/Dump وAccess (.mdb/.accdb)', paste: 'ألصق CSV أو JSON هنا', preview: 'معاينة: {count} صف', importing: 'جار الاستيراد...', importRows: 'استيراد {count} صف' },
    language: 'اللغة',
    brand: { name: 'School Store', tagline: 'إدارة مدرسية' },
    theme: { label: 'المظهر', system: 'النظام', light: 'فاتح', dark: 'داكن' },
    layout: { openMenu: 'فتح القائمة', closeMenu: 'إغلاق القائمة' },
    languages: { fr: 'Français', en: 'English', es: 'Español', ar: 'العربية' },
    nav: { dashboard: 'لوحة التحكم', products: 'المنتجات', categories: 'الفئات', clients: 'العملاء', reports: 'التقارير', team: 'الفريق', newInvoice: 'فاتورة جديدة', invoices: 'الفواتير' },
    pages: { dashboard: 'لوحة التحكم', products: 'إدارة المنتجات', categories: 'إدارة الفئات', clients: 'إدارة العملاء', reports: 'التقارير والإحصائيات', team: 'الفريق والمؤسسة', newInvoice: 'فاتورة جديدة', invoices: 'سجل الفواتير', detail: 'تفاصيل الفاتورة' },
    actions: { logout: 'تسجيل الخروج', recent: 'الفواتير الأخيرة', viewAll: 'عرض الكل', refresh: 'تحديث' },
    dashboard: { products: 'المنتجات', categories: 'الفئات', clients: 'العملاء', invoices: 'إجمالي الفواتير', pending: 'الفواتير المعلقة', revenue: 'الإيرادات', lowStock: 'مخزون منخفض', createInvoice: 'إنشاء فاتورة', manageProducts: 'إدارة المنتجات', manageClients: 'إدارة العملاء', history: 'عرض السجل', noInvoices: 'لا توجد فواتير', greeting: 'مرحباً، {name}', welcomeCopy: 'تابع نشاط متجرك المدرسي بنظرة سريعة.', unknownClient: 'العميل غير محدد' },
    status: { paid: 'مدفوعة', pending: 'معلقة', cancelled: 'ملغاة' },
    common: { save: 'حفظ', cancel: 'إلغاء', edit: 'تعديل', delete: 'حذف', loading: 'جار التحميل...', none: 'لا يوجد', search: 'بحث', import: 'استيراد جماعي', importHint: 'يمكنك أيضاً لصق البيانات يدوياً. يجب أن يحتوي الصف الأول من CSV على أسماء الأعمدة.', create: 'إنشاء', close: 'إغلاق', name: 'الاسم', email: 'البريد الإلكتروني', phone: 'الهاتف', address: 'العنوان', description: 'الوصف', notes: 'ملاحظات', price: 'السعر', stock: 'المخزون', barcode: 'الرمز الشريطي', category: 'الفئة', image: 'الصورة', allStatuses: 'كل الحالات', noResults: 'لا توجد نتائج', notFound: 'الصفحة غير موجودة' },
    login: { subtitle: 'سجل الدخول للمتابعة', signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب', fullName: 'الاسم الكامل', role: 'الدور', agent: 'موظف الصندوق', manager: 'مدير', password: 'كلمة المرور', wait: 'انتظر...', submitSignIn: 'تسجيل الدخول', submitSignUp: 'إنشاء الحساب', demo: 'حساب تجريبي (SQLite)', adapter: 'المحول النشط' },
    productsView: { title: 'المنتجات', new: 'منتج جديد', noProducts: 'لا توجد منتجات', edit: 'تعديل المنتج', newTitle: 'منتج جديد', imageUrl: 'رابط الصورة أو الملف', noCategory: 'لا شيء', importing: 'استيراد المنتجات', inStock: 'في المخزون', scanBarcode: 'مسح الرمز الشريطي', scanProduct: 'مسح المنتج', barcodeHint: 'امسح الرمز بالكاميرا أو أدخله يدوياً.', duplicateBarcode: 'هذا الرمز مرتبط بالفعل بالمنتج «{name}».', adjustStock: 'تعديل المخزون', adjustStockTitle: 'تعديل مخزون: {name}', adjustCurrentStock: 'المخزون الحالي', adjustQuantity: 'الكمية (+ أو -)', adjustQuantityHint: 'استخدم قيمة موجبة للإضافة وسالبة للسحب.', adjustReason: 'السبب', adjustSubmit: 'تطبيق', reasonCorrection: 'تصحيح المخزون', reasonRestock: 'إعادة التخزين', reasonDamage: 'منتج تالف', reasonLoss: 'فقدان / سرقة', reasonOther: 'آخر', lowStockThreshold: 'حد المخزون المنخفض', lowStockThresholdHint: 'اتركه فارغاً لاستخدام الحد الافتراضي للتطبيق.' },
    categoriesView: { title: 'الفئات', new: 'فئة جديدة', edit: 'تعديل الفئة', importing: 'استيراد الفئات' },
    clientsView: { title: 'العملاء', new: 'عميل جديد', edit: 'تعديل العميل', importing: 'استيراد العملاء', discount: 'الخصم العام (%)', pricing: 'سعر منتج خاص', noClients: 'لا يوجد عملاء', noClient: 'بدون عميل', balanceDue: 'الرصيد المستحق', statement: 'كشف الحساب', statementTitle: 'كشف حساب: {name}', statementEmpty: 'لا توجد فواتير غير مدفوعة.' },
    reports: { title: 'التقارير', dateFrom: 'من', dateTo: 'إلى', thisMonth: 'هذا الشهر', last7Days: 'آخر 7 أيام', allTime: 'كل الفترات', totalRevenue: 'الإيرادات', invoiceCount: 'الفواتير', averageSale: 'متوسط البيع', outstandingBalance: 'الرصيد غير المدفوع', topProducts: 'أفضل المنتجات مبيعاً', topClients: 'أفضل العملاء', salesByAgent: 'المبيعات حسب الموظف', product: 'المنتج', quantitySold: 'الكمية المباعة', revenue: 'الإيرادات', client: 'العميل', agent: 'الموظف', noData: 'لا توجد بيانات لهذه الفترة', exportCsv: 'تصدير CSV' },
    team: { title: 'الفريق', unavailable: 'إدارة الفريق تتطلب محول Supabase.', profileShortcut: 'إدارة المؤسسة والفريق', updateOrganization: 'تعديل المؤسسة', organizationName: 'اسم المؤسسة', organizationSlug: 'معرف الرابط', organizationUpdated: 'تم تحديث المؤسسة.', status: 'الحالة', currency: 'العملة', members: 'الأعضاء', member: 'عضو', noMembers: 'لا يوجد أعضاء', role: 'الدور', inviteUser: 'إنشاء مستخدم', inviteHint: 'سيتم إرسال بريد دعوة للمستخدم لتعيين كلمة المرور.', sendInvite: 'إرسال الدعوة', invitationSent: 'تم إرسال الدعوة.', roles: { owner: 'مالك', manager: 'مدير', cashier: 'أمين الصندوق', stockManager: 'مسؤول المخزون', accountant: 'محاسب', viewer: 'مشاهد' }, statuses: { active: 'نشط', invited: 'مدعو', suspended: 'موقوف' } },
    organizations: { title: 'المؤسسات', shortcut: 'إدارة المؤسسات', create: 'إنشاء مؤسسة', edit: 'تعديل المؤسسة', empty: 'لا توجد مؤسسات', name: 'الاسم', slug: 'معرف الرابط', status: 'الحالة', email: 'البريد الإلكتروني', phone: 'الهاتف', address: 'العنوان', active: 'نشطة', suspended: 'موقوفة', pending: 'معلقة', cancelled: 'ملغاة', manageTeam: 'إدارة الفريق', saved: 'تم حفظ المؤسسة.', deleted: 'تم حذف المؤسسة.', confirmDelete: 'حذف {name}؟' },
    profile: { title: 'ملفي الشخصي', shortcut: 'إدارة ملفي الشخصي', fullName: 'الاسم الكامل', role: 'الدور', saved: 'تم تحديث الملف الشخصي.' },
    invoicesView: { title: 'سجل الفواتير', search: 'بحث (رقم الفاتورة، العميل...)', selectAll: 'تحديد جميع الفواتير', invoiceNumber: 'رقم الفاتورة', createdBy: 'أنشأها', client: 'العميل', date: 'التاريخ', total: 'الإجمالي', status: 'الحالة', actions: 'الإجراءات', noInvoices: 'لا توجد فواتير', view: 'عرض الفاتورة', delete: 'حذف الفاتورة', bulkDelete: 'حذف الفواتير المحددة', confirmDelete: 'حذف الفاتورة {number}؟', confirmBulk: 'حذف {count} فاتورة محددة؟' },
    invoiceCreate: { productSearch: 'البحث بالاسم أو الرمز الشريطي', clientSearch: 'بحث عن عميل (الاسم أو البريد أو الهاتف)', selectedClient: 'العميل المحدد: {name}', customerName: 'اسم العميل (اختياري)', empty: 'السلة فارغة', scanHint: 'امسح منتجاً أو استخدم الإدخال اليدوي', clear: 'إفراغ', payment: 'الدفع', received: 'المبلغ المستلم', change: 'الباقي', remaining: 'المبلغ المتبقي', validate: 'تأكيد الفاتورة', success: 'تم تأكيد الفاتورة بنجاح!' },
    pos: { subtotal: 'المجموع الفرعي', discount: 'الخصم', total: 'الإجمالي', proceedPayment: 'المتابعة إلى الدفع', addProduct: 'إضافة منتج', chooseClient: 'اختيار عميل', clearCart: 'إفراغ السلة', processingPayment: 'جار التحقق...', outOfStock: 'نفد المخزون', stockAvailable: 'المخزون: {stock}', inCart: 'في السلة: {quantity}', amountReceived: 'المبلغ المستلم', paymentMethod: 'طريقة الدفع', discountPercent: 'الخصم (%)', changeDue: 'الباقي المستحق', quickAmounts: 'مبالغ سريعة', cash: 'نقداً', card: 'بطاقة', transfer: 'تحويل بنكي', other: 'أخرى', quantityOf: 'كمية {name}', decreaseQuantity: 'تقليل الكمية', increaseQuantity: 'زيادة الكمية', unitPrice: 'سعر الوحدة', lineTotal: 'الإجمالي', removeFromInvoice: 'إزالة {name}', removeFromInvoiceTitle: 'إزالة من الفاتورة', stock: 'المخزون: {stock}' },
    detail: { back: 'رجوع', date: 'التاريخ', customer: 'العميل', createdBy: 'أنشأها', status: 'الحالة', product: 'المنتج', quantity: 'الكمية', unitPrice: 'سعر الوحدة', total: 'الإجمالي', print: 'طباعة', paid: 'المدفوع', delete: 'حذف الفاتورة', subtotal: 'المجموع الفرعي', discount: 'الخصم', remaining: 'المبلغ المتبقي', paymentHistory: 'سجل المدفوعات', noPayments: 'لا توجد مدفوعات مسجلة.', returnItems: 'إرجاع منتجات', returned: 'تم إرجاع {count}', returnMax: 'الحد الأقصى {max}', noReturnableItems: 'لا توجد منتجات قابلة للإرجاع', confirmReturn: 'تأكيد الإرجاع' },
    scanner: { activate: 'اضغط لتفعيل الماسح', start: 'بدء الماسح', retry: 'إعادة المحاولة', stop: 'إيقاف', manual: 'إدخال يدوي', code: 'الرمز الشريطي أو QR', validate: 'تأكيد', last: 'آخر رمز ممسوح', useDatalogic: 'استخدام ماسح Datalogic', hardwareScanner: 'ماسح Datalogic', waitingForScan: 'في انتظار مسح الرمز الشريطي...' },
    hardware: { title: 'المعدات', scanner: 'ماسح Datalogic', printer: 'طابعة حرارية', connect: 'اتصل', disconnect: 'قطع الاتصال', connected: 'متصل', disconnected: 'غير متصل', autoScan: 'الماسح التلقائي', autoPrint: 'الطباعة التلقائية بعد الدفع', testPrint: 'اختبار الطباعة' }
  }
}

const supportedLocales = Object.keys(messages)
const savedLocale = localStorage.getItem('school-store-locale')
const browserLocale = navigator.language?.slice(0, 2)
const locale = supportedLocales.includes(savedLocale) ? savedLocale : supportedLocales.includes(browserLocale) ? browserLocale : 'fr'

document.documentElement.lang = locale
document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'

export const i18n = createI18n({ legacy: false, locale, fallbackLocale: 'fr', messages })

export function setLocale(nextLocale) {
  if (!supportedLocales.includes(nextLocale)) return
  i18n.global.locale.value = nextLocale
  localStorage.setItem('school-store-locale', nextLocale)
  document.documentElement.lang = nextLocale
  document.documentElement.dir = nextLocale === 'ar' ? 'rtl' : 'ltr'
}

export { supportedLocales }
